### ISSUE TITLE
ISO_19794_2_2005  support

### ISSUE THREAD

**Issue by zengsentry** [robertvazan/sourceafis-java#25]
import a initial ISO_19794_2_2005 format .dat file and covert to  FingerprintTemplate, then export it by ISO_19794_2_2005 format.
However  matchs both initial and final .dat and there is no match.

**Comment by robertvazan** [comment]
I cannot understand what are you saying.

**Comment by kpoman** [comment]
I suppose I understood he imports an ISO then exports it then matchs both initial and final .dat and there is no match, which would imply erros wether on input conv or output conv ?

**Comment by robertvazan** [comment]
I figured that much, but it makes no sense. A snipped, expected and actual output would help. Some explanation how the OP came to that would also help improve the docs.

**Comment by zengsentry** [comment]
> I suppose I understood he imports an ISO then exports it then matchs both initial and final .dat and there is no match, which would imply erros wether on input conv or output conv ?

Yes, you are right.

**Comment by zengsentry** [comment]
Hi robertvazan 
    Any recommend for ISO_19794_2_2005 format convert?

**Comment by robertvazan** [comment]
I still don't understand the issue here. SourceAFIS mainline can import ISO 19794-2:2005 within limits of its current public description:

https://templates.machinezoo.com/iso-19794-2-2005

SourceAFIS doesn't do ISO template export yet as that would require information from the expensive ISO specs. I can nevertheless provide it for a fee (full ANSI378 support was also added thanks to a sponsor).

So it is not clear to me what are you doing since one of the steps in your description (export to ISO 19794-2) is not currently possible.

**Comment by zengsentry** [comment]
As I  compared  both iso-19794-2-2005 and  ANSI378 specs，I foud  only a few  field different. so I changed the  SourceAFIS source code then do some export to ISO 19794-2 testing.

![image](https://user-images.githubusercontent.com/17687248/77534480-aeeace00-6ed3-11ea-8b4c-2d92af02bb37.png)
 
`	/**
         *  ForeignTemplate.java 
	 *  template export  
	 * @param out
	 * @throws IOException
	 */
	void write(DataOutputStream out) throws IOException {
		//TODO ? IllegalStateException  ISO_19794_2_2005
//		if (format == ForeignFormat.ISO_19794_2_2005)
//			throw new IllegalStateException();
		//head
		writeFormatMarker(out);
		//version code
		writeVersion(out); 
		writeTemplateLength(out); 
		//ISO_19794_2_2005  skip it
		if (format != ForeignFormat.ISO_19794_2_2005){
			writeProductId(out);
		}
		writeSensorInfo(out);
//		if (format == ForeignFormat.ANSI_378_2004){
//			dimensions.write(out);
//		}
         //X image size Y image size X resolution Y resolution # of finger views Reserved byte
		if (format == ForeignFormat.ANSI_378_2004 ||format == ForeignFormat.ISO_19794_2_2005 ){
			dimensions.write(out);
		}
		//off views 01
		writeFingerprintCount(out);
        //Reserved byte 00
		out.writeByte(0);  
		// Single Finger View Minutiae Record 
		for (int i = 0; i < fingerprints.size(); ++i){
			fingerprints.get(i).write(out, format, i);
		}  
	}`

**Comment by robertvazan** [comment]
So it is clear now. You are testing your own quick ISO 19794-2 implementation. Simply adjusting field structure is not sufficient. There are semantic differences. I dimly remember the angle encoding is different. There might be new required fields, so even if you manage to successfully roundtrip the format, the templates might still be rejected by 3rd party software.

I am closing this issue since it is about your own code rather than about SourceAFIS.

**Comment by zengsentry** [comment]
Thanks robertvazan,   you are right, the angle encoding is different.
do you have any recommend ?
