### ISSUE TITLE
Fastutil library too big for client apps

### ISSUE THREAD

**Issue by tsayao** [robertvazan/sourceafis-java#32]
The fastutil dependency adds more or less 18mb. It's too big for general desktop apps that would use sourceafis.

**Comment by robertvazan** [comment]
Isn't there some sort of Maven plugin that bundles the app with all libraries in single JAR and kills off unused classes in the process? I know this cannot be done in general due to dynamic class references, but it can be safely enabled for fastutil packages.

Anyway, is this actually causing some practical problems besides somewhat longer download?

**Comment by tsayao** [comment]
Not that I know of, at least on class level.

Well, if you think one machine, it's ok. May be a problem for 3.000+ machines.

I came across this when trying to make the a diet on the app "fat jar". 18mb is a little to much for a library.

**Comment by robertvazan** [comment]
Check out [minimizeJar](https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html) in [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/). This solves the problem neatly for all libraries in all applications.
