### ISSUE TITLE
Is SourceAFIS portable to embedded systems? (C/C++)

### ISSUE THREAD

**Issue by NicksonYap** [robertvazan/sourceafis-java#4]
Nice to see the repo still maintained.

I'm looking into using this source code for performing 1:1 matching using the same kind of fingerprint sensor found in smartphones, but placed into a 32-bit ARM micro controller (limited RAM ~128kb)
The fingerprint sensor outputs individual pixels, roughly 160*160px

Any possibility of porting this into an embedded system?
Or does this require too much RAM or rely on advanced libraries?

**Comment by robertvazan** [comment]
There will never be a C/C++ version of SourceAFIS, because C/C++ code is hopelessly insecure and unstable. There might be a Rust port, but it's not on my current priority list. If you want to port it yourself, it's possible, but feature extractor as currently implemented will be very slow. With that amount of RAM, you will have to replace all double arrays with 8-bit integer arrays. Algorithm transparency in the upcoming 3.x version might help you to debug the code.
