### ISSUE TITLE
Matching Speed 

### ISSUE THREAD

**Issue by musabeny** [robertvazan/sourceafis-java#47]
Hi
I can't reach a speed of 12500fp/s per core my processor is 2.19GHz  see my code below

FingerprintMatcher matcher = new FingerprintMatcher(probe);
        UserDetails match = null;
         double high = 0;
         AtomicReference<Double> highAtom = new AtomicReference<>((double) 0);
        logger.info("Start parallel comparing finge");
        long startTime = System.currentTimeMillis();
        candidates.parallelStream().forEach(candidate -> {
            double score = matcher.match(returnTemplateFromBytre(candidate.getFingerPrint()));
            if (score > highAtom.get()) {
                highAtom.set(score);
//                match = candidate;
            }
        });
        logger.info("End parallel comparing finge "+highAtom.get());
        long stopTime = System.currentTimeMillis();
        logger.info("parallel solution time: " + (stopTime - startTime));

**Comment by robertvazan** [comment]
That speed was measured on a 3.5GHz Intel core. It also varies somewhat with population (smaller fingerprints are faster). What speed are you observing?

**Comment by musabeny** [comment]
i have 77473 fingerprint and it take 44330ms

**Comment by robertvazan** [comment]
1.7Kfp/s is quite slow, especially since the code is parallelized. This seems to be caused by deserialization in the loop. Deserialization of fingerprints is slower than matching. You should keep all fingerprints in deserialized form in RAM.

BTW, there's a race rule in your code. You should protect the whole best match code with synchronization instead of using AtomicReference, which would not work in this case.
